local GameGUISystem = require('src.systems.game.gui.gui_system')

function init(self)
    GameGUISystem:init()
end

function on_message(self, message_id, message, sender)
    GameGUISystem:on_message(message_id, message, sender)
end

function on_input(self, action_id, action)
    if action_id then
        GameGUISystem:on_input(action_id, action)
    end
end

function final(self)
    GameGUISystem:final()
end
