local App = require('src.app')
local GameServices = require('src.systems.game.services.services')

local GameMsgService = GameServices.msg
local MSG = App.constants.messages.common

function init(self)
    self.id = go.get_id()
end

function on_message(self, message_id, message, sender)
    if message_id == MSG.collision_response then
        GameMsgService:send(self.id, message_id, message)
    end
end
