local GameSystem = require('src.systems.game_system')
local Services = require('src.services.services')

local ScreenService = Services.screen

function init(self)
    msg.post('.', 'acquire_input_focus')

    GameSystem:init()
    ScreenService:add_listener(msg.url())
end

function on_message(self, message_id, message, sender)
    ScreenService:on_message(message_id)
end

function update(self, dt)

end

function on_input(self, action_id, action)
    GameSystem:on_input(action_id, action)
end
