local App = require('src.app')
local GameSystem = require('src.systems.game.go_system')

function init(self)
    GameSystem:init()
end

function on_message(self, message_id, message, sender)
    GameSystem:on_message(message_id, message)
end

function on_input(self, action_id, action)
    if action_id then
        GameSystem:on_input(action_id, action)
    end
end

function final(self)
    GameSystem:final()
end
