local App = require('src.app')
local GameServices = require('src.systems.game.services.services')

local SceneMsgService = GameServices.msg

local MSG = App.constants.messages.common
local GameSceneUrls = App.constants.urls.scenes.game_scene

function init(self)
    self.id = GameSceneUrls.losing_zone
end

function on_message(self, message_id, message, sender)
    if message_id == MSG.collision_response then
        SceneMsgService:send(self.id, message_id, message)
    end
end
