local GUISystem = require('src.systems.game pause popup.gui_system')

function init(self)
    GUISystem:init()
    gui.set_render_order(15)
end

function on_message(self, message_id, message, sender)
    GUISystem:on_message(message_id, message, sender)
end

function on_input(self, action_id, action)
    if action_id then
        GUISystem:on_input(action_id, action)
    end
end

function final(self)
    GUISystem:final()
end
